add some terraform best practices

diff --git a/.github/workflows/infra_backend.yml b/.github/workflows/infra_backend.yml
--- a/.github/workflows/infra_backend.yml
+++ b/.github/workflows/infra_backend.yml
@@ -50,12 +50,19 @@ jobs:
         id: init
         run: terraform init
 
+      - name: Terraform format
+        id: fmt
+        run: terraform fmt -check
+
       - name: Terraform Validate
         id: validate
         run: terraform validate
 
       - name: Terraform Plan
-        run: terraform plan -out=tfplan
+        id: plan
+        run: |
+          terraform plan -no-color -input=false -out=tfplan || echo "PLAN_FAILED=true" >> $GITHUB_ENV
+        continue-on-error: true
 
       - name: Save Terraform Plan
         uses: actions/upload-artifact@v4
@@ -64,8 +71,8 @@ jobs:
           path: tfplan
 
       - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
+        if: env.PLAN_FAILED == 'true'
         run: exit 1
 
       - name: Terraform Apply
-        run: terraform apply tfplan -auto-approve
+        run: terraform apply -input=false -auto-approve tfplan
